# .github/workflows/deploy-being-adept-slack-bot.yml

name: Deploy Slack Bot

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add host key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        APP_DIR: ${{ secrets.APP_DIR }}
      run: |
        ssh $SERVER_USER@$SERVER_IP "
          cd $APP_DIR && \
          git pull origin main && \
          source venv/bin/activate && \
          pip install -r requirements.txt && \
          
          # Restart the systemd service
          echo 'Restarting being-adept-slack-bot service...'
          sudo systemctl restart being-adept-slack-bot && \
          
          # Check if service started successfully
          sleep 5
          if sudo systemctl is-active --quiet being-adept-slack-bot; then
            echo 'Service started successfully!'
            echo 'Service status:'
            sudo systemctl status being-adept-slack-bot --no-pager | head -n 15
          else
            echo 'ERROR: Service failed to start!'
            sudo systemctl status being-adept-slack-bot --no-pager
            exit 1
          fi
        "
